login: &login
  username: hb_web
  password: devonly:l/8H/6wiGKarJoAaz6GmJEOIcnKfQNHhq6BAttO4jJSZrwTOEE
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  port: 5432

development:
  <<: *login
  database: hb_development

production:
  <<: *login
  database: hb_development

test:
  <<: *login
  database: hb_test