# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88b2be3d9d9d7de2e2b435dfadb3344e9eda546470911b88b8281dfa5acabf235e3fa9e91d3eac256c81170a5905884e94dcff98defa711bcff3ebde71fda202

test:
  secret_key_base: 01067185df22da8010067e00a0fed290f74f2a55a6596640e214880ed2e9a838707909d12c725b3f3d185d0113dab610b4950e2f944689df5708a6e26f410d74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
